from fractions import Fraction
from typing import Any, Callable, List, Optional, Union

class STree:
    children: Optional[List["STree"]]

    def __init__(self) -> None: ...
    def insert_left(self, children: Optional[List["STree"]] = None) -> "STree": ...
    def insert_right(self, children: Optional[List["STree"]] = None) -> "STree": ...
    @staticmethod
    def parse(s: str) -> "STree": ...
    def degree(self) -> int: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def is_leaf(self) -> bool: ...

class Tridend:
    @staticmethod
    def unit() -> "Tridend": ...
    @staticmethod
    def to_vec(tree: "STree") -> "Tridend": ...
    @classmethod
    def linear_map(
        cls, func: Callable[[STree], "Tridend"]
    ) -> Callable[["Tridend"], "Tridend"]: ...
    def outer(self, other: "Tridend") -> "Tridend": ...
    def vee(*trees: "Tridend") -> "Tridend": ...
    def prec_sh(self, other: "Tridend") -> "Tridend": ...
    def prec_qsh(self, other: "Tridend") -> "Tridend": ...
    def succ_sh(self, other: "Tridend") -> "Tridend": ...
    def succ_qsh(self, other: "Tridend") -> "Tridend": ...
    def dot(self, other: "Tridend") -> "Tridend": ...
    def coprod_sh(self) -> "Tridend": ...
    def coprod_qsh(self) -> "Tridend": ...
    def __add__(self, other: "Tridend") -> "Tridend": ...
    def __sub__(self, other: "Tridend") -> "Tridend": ...
    def __rmul__(self, other: Union[Fraction, int]) -> "Tridend": ...
    def __mul__(self, other: "Tridend") -> "Tridend": ...
    def __matmul__(self, other: "Tridend") -> "Tridend": ...
