from typing import Any, List, Optional

class STree:
    children: Optional[List["STree"]]

    def __init__(self) -> None: ...
    def insert_left(self, children: Optional[List["STree"]] = None) -> "STree": ...
    def insert_right(self, children: Optional[List["STree"]] = None) -> "STree": ...
    @staticmethod
    def parse(s: str) -> "STree": ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def is_leaf(self) -> bool: ...

class Tridend:
    @staticmethod
    def unit() -> "Tridend": ...
    def vee(*trees: "Tridend") -> "Tridend": ...
    def prec_sh(self, other: "Tridend") -> "Tridend": ...
    def prec_qsh(self, other: "Tridend") -> "Tridend": ...
    def succ_sh(self, other: "Tridend") -> "Tridend": ...
    def succ_qsh(self, other: "Tridend") -> "Tridend": ...
    def dot(self, other: "Tridend") -> "Tridend": ...
    def __mul__(self, other: "Tridend") -> "Tridend": ...
    def __matmul__(self, other: "Tridend") -> "Tridend": ...
