from typing import Optional, Dict
from fractions import Fraction
from collections import UserDict

class Vector(UserDict):
    def __init__(self, data: Optional[Dict[Any, Fraction]] = None) -> None: ...
    @classmethod
    def to_vec(cls, b: Any) -> 'Vector': ...
    def __reduce(self) -> None: ...
    def __add__(self, other: 'Vector') -> 'Vector': ...
    def __neg__(self) -> 'Vector': ...
    def __sub__(self, other: 'Vector') -> 'Vector': ...
    def __repr__(self) -> str: ...
    def is_zero(self) -> bool: ...
    def __rmul__(self, k: Fraction) -> 'Vector': ...
    def __rmatmul__(self, k: Fraction) -> 'Vector': ...
    @classmethod
    def linear_map(cls, func: Any) -> Any: ...
